//ANNOUNCEMENTS
export const REFRESH_ANNOUNCEMENTS = "REFRESH_ANNOUNCEMENTS"

//ADD ANNOUNCEMENT
export const CHANGE_TITLE = "CHANGE_TITLE"
export const OPEN_FORM = "OPEN_FORM"
export const CHANGE_DESCRIPTION = "CHANGE_DESCRIPTION"
export const DESCRIPTION_ERROR = "DESCRIPTION_ERROR"
export const TITLE_ERROR = "TITLE_ERROR"
export const CLEAR_FORM = "CLEAR_FORM"
export const REMOVE_TITLE_BORDER = "REMOVE_TITLE_BORDER"
export const REMOVE_DESCRIPTION_BORDER = "REMOVE_DESCRIPTION_BORDER"

//ANNOUNCEMENT ACTIONS 
export const SHOW_EDIT_TITLE_FORM = "SHOW_EDIT_TITLE_FORM"
export const HIDE_EDIT_TITLE_FORM = "HIDE_EDIT_TITLE_FORM"
export const SHOW_EDIT_TEXT_FORM = "SHOW_EDIT_TEXT_FORM"
export const HIDE_EDIT_TEXT_FORM = "HIDE_EDIT_TEXT_FORM"

//SEARCH
export const CHANGE_SEARCH_VALUE = "CHANGE_SEARCH_VALUE"
export const SEARCH_RESULT = "SEARCH_RESULT"
export const CLEAR_SEARCH_VALUE = "CLEAR_SEARCH_VALUE"
