//ANNOUNCEMENTS
export const REFRESH_ANNOUNCEMENTS = "REFRESH_ANNOUNCEMENTS"

//ADD ANNOUNCEMENT
export const CHANGE_TITLE = "CHANGE_TITLE"
export const CHANGE_DESCRIPTION = "CHANGE_DESCRIPTION"
export const DESCRIPTION_ERROR = "DESCRIPTION_ERROR"
export const TITLE_ERROR = "TITLE_ERROR"
export const CLEAR_FORM = "CLEAR_FORM"
export const REMOVE_TITLE_BORDER = "REMOVE_TITLE_BORDER"
export const REMOVE_DESCRIPTION_BORDER = "REMOVE_DESCRIPTION_BORDER"
